"""Add salt column to sessions

Revision ID: 83865d7a977d
Revises: 458be9326612
Create Date: 2024-11-06 20:47:24.231407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83865d7a977d'
down_revision = '458be9326612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
